In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_train = pd.read_csv('/kaggle/UsedCars/train.csv')
df_test = pd.read_csv('/kaggle/UsedCars/test.csv')
df_sub = pd.read_csv('/kaggle/UsedCars/sample_submission.csv')

In [5]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [7]:
df_train.isna().sum()[df_train.isna().sum() != 0]

fuel_type       5083
accident        2452
clean_title    21419
dtype: int64

In [8]:
df_train['fuel_type'].value_counts()

fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64

In [9]:
df_test['fuel_type'].value_counts()

fuel_type
Gasoline          110533
Hybrid              4676
E85 Flex Fuel       3523
Diesel              2686
–                    538
Plug-In Hybrid       337
not supported         14
Name: count, dtype: int64

In [10]:
df_train[df_train['fuel_type'] == '-']

Empty DataFrame
Columns: [id, brand, model, model_year, milage, fuel_type, engine, transmission, ext_col, int_col, accident, clean_title, price]
Index: []

In [11]:
df_train['fuel_type'] = df_train['fuel_type'].fillna('Gasoline')
df_test['fuel_type'] = df_test['fuel_type'].fillna('Gasoline')

In [12]:
df_train['accident'].value_counts()

accident
None reported                             144514
At least 1 accident or damage reported     41567
Name: count, dtype: int64

In [13]:
df_test['accident'].value_counts()

accident
None reported                             96263
At least 1 accident or damage reported    27795
Name: count, dtype: int64

In [14]:
df_train['accident'] = df_train['accident'].fillna(np.random.choice(a=['None reported', 'At least 1 accident or damage reported'], p = [0.7, 0.3]))
df_test['accident'] = df_test['accident'].fillna(np.random.choice(a=['None reported', 'At least 1 accident or damage reported'], p = [0.7, 0.3]))

In [15]:
df_test['clean_title'].value_counts()

clean_title
Yes    111451
Name: count, dtype: int64

In [16]:
df_train = df_train.drop('clean_title', axis=1)
df_test = df_test.drop('clean_title', axis=1)

In [17]:
df_train = df_train.drop('id', axis=1)
df_test = df_test.drop('id', axis=1)

In [18]:
df_train.isna().sum()[df_train.isna().sum() != 0]

Series([], dtype: int64)

In [19]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   brand         188533 non-null  object
 1   model         188533 non-null  object
 2   model_year    188533 non-null  int64
 3   milage        188533 non-null  int64
 4   fuel_type     188533 non-null  object
 5   engine        188533 non-null  object
 6   transmission  188533 non-null  object
 7   ext_col       188533 non-null  object
 8   int_col       188533 non-null  object
 9   accident      188533 non-null  object
 10  price         188533 non-null  int64
dtypes: int64(3), object(8)
memory usage: 15.8+ MB

In [20]:
set(df_test['brand'].unique()).difference(set(df_train['brand'].unique()))

set()

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
label = LabelEncoder()

In [23]:
df_train['brand'] = label.fit_transform(df_train['brand'])
df_test['brand'] = label.transform(df_test['brand'])

In [24]:
df_train['model']

0                    Cooper S Base
1                            LS V8
2                Silverado 2500 LT
3                 G90 5.0 Ultimate
4                      Metris Base
                    ...
188528       Escalade ESV Platinum
188529    AMG C 43 AMG C 43 4MATIC
188530      AMG GLC 63 Base 4MATIC
188531            S5 3.0T Prestige
188532                  Macan Base
Name: model, Length: 188533, dtype: object

In [25]:
set(df_test['model'].unique()).difference(set(df_train['model'].unique()))

{'allroad 2.7T'}

In [26]:
df_test['model'].value_counts()['allroad 2.7T']

np.int64(1)

In [27]:
df_test['model'] = df_test['model'].replace('allroad 2.7T', 'F-150 XLT')

In [28]:
df_train['model'] = label.fit_transform(df_train['model'])
df_test['model'] = label.transform(df_test['model'])

In [29]:
set(df_test['fuel_type'].unique()).difference(set(df_train['fuel_type'].unique()))

set()

In [30]:
df_train['fuel_type'] = label.fit_transform(df_train['fuel_type'])
df_test['fuel_type'] = label.transform(df_test['fuel_type'])

In [31]:
set(df_test['engine'].unique()).difference(set(df_train['engine'].unique()))

{'177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas'}

In [32]:
df_train['engine'].value_counts()

engine
355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel           3462
240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel           2902
420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel           2841
2.0L I4 16V GDI DOHC Turbo                             2680
375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel          2451
                                                       ...
78.0HP 1.2L 3 Cylinder Engine Gasoline Fuel               1
139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas       1
151.0HP 1.5L 4 Cylinder Engine Gas/Electric Hybrid        1
184.0HP 2.4L 4 Cylinder Engine Flex Fuel Capability       1
313.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas       1
Name: count, Length: 1117, dtype: int64

In [33]:
df_test[df_test['engine'] == '177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas']

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident
54866,24,1606,2023,5500,2,177.0HP 1.6L 4 Cylinder Engine Plug-In Electri...,A/T,White,Black,None reported
105633,24,1606,2015,156350,4,177.0HP 1.6L 4 Cylinder Engine Plug-In Electri...,A/T,White,White,At least 1 accident or damage reported
111992,9,1606,2023,1340,4,177.0HP 1.6L 4 Cylinder Engine Plug-In Electri...,9-Speed A/T,Black,Black,None reported
117012,24,1606,2022,1340,2,177.0HP 1.6L 4 Cylinder Engine Plug-In Electri...,A/T,Gray,Black,None reported

In [34]:
df_test['engine'] = df_test['engine'].replace('177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas', '139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas')

In [35]:
df_train['engine'] = label.fit_transform(df_train['engine'])
df_test['engine'] = label.transform(df_test['engine'])

In [36]:
set(df_test['transmission'].unique()).difference(set(df_train['transmission'].unique()))

set()

In [37]:
df_train['transmission'] = label.fit_transform(df_train['transmission'])
df_test['transmission'] = label.transform(df_test['transmission'])

In [38]:
set(df_test['ext_col'].unique()).difference(set(df_train['ext_col'].unique()))

set()

In [39]:
df_train['ext_col'] = label.fit_transform(df_train['ext_col'])
df_test['ext_col'] = label.transform(df_test['ext_col'])

In [40]:
set(df_test['int_col'].unique()).difference(set(df_train['int_col'].unique()))

set()

In [41]:
df_train['int_col'] = label.fit_transform(df_train['int_col'])
df_test['int_col'] = label.transform(df_test['int_col'])

In [42]:
set(df_test['accident'].unique()).difference(set(df_train['accident'].unique()))

set()

In [43]:
df_train['accident'] = label.fit_transform(df_train['accident'])
df_test['accident'] = label.transform(df_test['accident'])

In [44]:
df_train.corr()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
brand,1.000000,-0.040049,-0.014605,-0.007286,0.043534,-0.065512,0.036984,0.006038,-0.004765,0.005945,0.017657
model,-0.040049,1.000000,0.001784,0.041706,0.009617,-0.042079,-0.027031,0.007560,0.076990,-0.018724,-0.029865
model_year,-0.014605,0.001784,1.000000,-0.669936,0.010908,0.285300,0.043596,-0.032189,0.024833,0.243245,0.231795
milage,-0.007286,0.041706,-0.669936,1.000000,-0.105261,-0.331196,-0.041158,0.027763,-0.030846,-0.305386,-0.283067
fuel_type,0.043534,0.009617,0.010908,-0.105261,1.000000,0.020990,0.093713,-0.010751,0.004114,0.037767,0.015427
engine,-0.065512,-0.042079,0.285300,-0.331196,0.020990,1.000000,-0.017717,-0.037814,0.006319,0.154995,0.208285
transmission,0.036984,-0.027031,0.043596,-0.041158,0.093713,-0.017717,1.000000,0.005435,-0.002534,-0.008882,0.014560
ext_col,0.006038,0.007560,-0.032189,0.027763,-0.010751,-0.037814,0.005435,1.000000,0.067904,-0.018092,-0.017342
int_col,-0.004765,0.076990,0.024833,-0.030846,0.004114,0.006319,-0.002534,0.067904,1.000000,-0.001983,0.035174
accident,0.005945,-0.018724,0.243245,-0.305386,0.037767,0.154995,-0.008882,-0.018092,-0.001983,1.000000,0.118315
price,0.017657,-0.029865,0.231795,-0.283067,0.015427,0.208285,0.014560,-0.017342,0.035174,0.118315,1.000000

In [45]:
df_test

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident
0,26,1390,2015,98000,2,325,16,304,10,1
1,26,1377,2020,9142,3,787,31,263,14,1
2,14,636,2022,28121,2,540,3,304,57,1
3,3,182,2016,61258,2,192,39,261,14,1
4,3,181,2018,59000,2,364,38,128,14,1
...,...,...,...,...,...,...,...,...,...,...
125685,36,760,2014,83315,2,732,23,29,14,1
125686,3,1250,2019,29336,2,510,39,304,14,1
125687,3,184,2012,77634,2,673,38,29,14,1
125688,3,1246,2012,112000,2,673,38,29,14,1
125689,9,1671,2018,66840,2,718,38,263,14,1

In [46]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [52]:
from sklearn.linear_model import LinearRegression

In [53]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
df_sub['price'] = y_pred

In [ ]:
df_sub.to_csv('sub.csv', index=False, index_label=False)

In [47]:
# Polynomial

In [48]:
from sklearn.preprocessing import PolynomialFeatures

In [49]:
poly = PolynomialFeatures(degree=3, include_bias=False)

In [50]:
X_train = poly.fit_transform(X_train)
X_test = poly.transform(X_test)

In [54]:
model = LinearRegression()

In [56]:
model.fit(X_train, y_train)

LinearRegression()

In [58]:
y_pred = model.predict(X_test)

In [59]:
df_sub['price'] = y_pred

In [60]:
df_sub.to_csv('subPlnm.csv', index=False, index_label=False)